spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
  elasticsearch:
    uris: http://${ES_HOST}:${ES_PORT}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GG_CLIENT_ID}
            client-secret: ${GG_CLIENT_SECRET}
            redirect-uri: ${server.base_url}${GG_URL_REDIRECT:/oauth2/callback/google}
            scope:
              - email
              - profile
server:
  base_url: http://localhost
  servlet:
    session:
      cookie:
        domain: localhost
fe_base_url: ${server.base_url}:5173
cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}
payment:
  vnPay:
    url: ${VNP_URL}
    returnUrl: http://localhost:8080/api/vnpay/payment-callback
    tmnCode: ${VNP_TMCODE}
    secretKey: ${VNP_SECRET_KEY}
    version: ${VNP_VER}
    command: ${VNP_COMD}
    orderType: ${VNP_TYPE}
gemini:
  api-key: ${GEMINI_API_KEY}
jwt:
  token:
    secret_Key: ${JWT_SECRET_KEY}
ghn:
  token: ${GHN_TOKEN}
  shop_id: ${GHN_SHOPID}