package com.haiemdavang.AnrealShop.mail;

public class MailTemplate {
    public static String getEmailHTML(String code, String userName) {
        return "<!DOCTYPE html>\r\n"
                + "<html>\r\n"
                + "<head>\r\n"
                + "    <meta charset=\"UTF-8\">\r\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
                + "    <title>OTP Verification</title>\r\n"
                + "    <style>\r\n"
                + "        body {\r\n"
                + "            font-family: 'Helvetica Neue', Arial, sans-serif;\r\n"
                + "            background-color: #f3f4f6;\r\n"
                + "            margin: 0;\r\n"
                + "            padding: 0;\r\n"
                + "        }\r\n"
                + "        .container {\r\n"
                + "            max-width: 600px;\r\n"
                + "            margin: 30px auto;\r\n"
                + "            background: #ffffff;\r\n"
                + "            padding: 30px;\r\n"
                + "            border-radius: 12px;\r\n"
                + "            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n"
                + "            text-align: center;\r\n"
                + "        }\r\n"
                + "        .header {\r\n"
                + "            font-size: 24px;\r\n"
                + "            font-weight: bold;\r\n"
                + "            color: #333;\r\n"
                + "            margin-bottom: 20px;\r\n"
                + "        }\r\n"
                + "        .username {\r\n"
                + "            font-size: 18px;\r\n"
                + "            font-weight: bold;\r\n"
                + "            color: #444;\r\n"
                + "            margin-top: 10px;\r\n"
                + "        }\r\n"
                + "        .otp {\r\n"
                + "            font-size: 28px;\r\n"
                + "            font-weight: bold;\r\n"
                + "            color: #ffffff;\r\n"
                + "            background: linear-gradient(135deg, #6e8efb, #a777e3);\r\n"
                + "            display: inline-block;\r\n"
                + "            padding: 15px 25px;\r\n"
                + "            border-radius: 8px;\r\n"
                + "            margin-top: 15px;\r\n"
                + "            letter-spacing: 2px;\r\n"
                + "        }\r\n"
                + "        .message {\r\n"
                + "            font-size: 16px;\r\n"
                + "            color: #555;\r\n"
                + "            margin-top: 10px;\r\n"
                + "        }\r\n"
                + "        .footer {\r\n"
                + "            margin-top: 30px;\r\n"
                + "            font-size: 12px;\r\n"
                + "            color: #888;\r\n"
                + "        }\r\n"
                + "    </style>\r\n"
                + "</head>\r\n"
                + "<body>\r\n"
                + "    <div class=\"container\">\r\n"
                + "        <div class=\"header\">🔐 OTP Verification</div>\r\n"
                + "        <p class=\"message\">Hello, <span class=\"username\">"+ userName + "</span>!</p>\r\n"
                + "        <p class=\"message\">Use the code below to complete your verification process:</p>\r\n"
                + "        <div class=\"otp\">"+ code + "</div>\r\n"
                + "        <p class=\"message\">This code will expire in 10 minutes. Please do not share it with anyone.</p>\r\n"
                + "        <div class=\"footer\">If you didn't request this OTP, please ignore this email.</div>\r\n"
                + "    </div>\r\n"
                + "</body>\r\n"
                + "</html>\r\n"
                + "";
    }
}
