ALTER TABLE `product_skus`
 ADD COLUMN sold TINYINT(1) DEFAULT 0;

ALTER TABLE products
    MODIFY COLUMN restrict_status ENUM('ALL', 'ACTIVE', 'VIOLATION', 'PENDING', 'HIDDEN')
    NOT NULL DEFAULT 'PENDING';